constant.ITEM_ITEMTYPE_WARSHIPDEBRIS = 1    --""
constant.ITEM_ITEMTYPE_HERODEBRIS = 2       --""
constant.ITEM_ITEMTYPE_TURRETDEBRIS = 3     --""
constant.ITEM_ITEMTYPE_SOLDIERSDEBRIS = 4   --""
constant.ITEM_ITEMTYPE_WARSHIPDRAWINGS = 5  --""
constant.ITEM_ITEMTYPE_HERODRAWINGS = 6     --""
constant.ITEM_ITEMTYPE_TURRETDRAWINGS = 7   --""
constant.ITEM_ITEMTYPE_SOLDIERSDRAWINGS = 8 --""

constant.ITEM_ITEMTYPE_WARSHIP = 9          --""
constant.ITEM_ITEMTYPE_HERO = 10            --""
constant.ITEM_ITEMTYPE_TURRET = 11          --""
constant.ITEM_ITEMTYPE_RESPLANETBUILD = 12  --""
constant.ITEM_ITEMTYPE_NFT_STAR = 131  --nft""

constant.ITEM_ITEMTYPE_NFT_ITEM = 13 -- nft""
constant.ITEM_ITEMTYPE_DAO_ITEM = 14  --dao""
constant.ITEM_ITEMTYPE_PROP = 15 -- ""
constant.ITEM_ITEMTYPE_SKILL_PIECES = 16 -- ""

constant.ITEM_CARDTICKET = 8720001  -- ""
constant.ITEM_SUPERCARDTICKET = 8720002 -- ""
