constant = constant or {}

require "common.constant.res"
require "common.constant.base"
require "common.constant.build"
require "common.constant.goods"
require "common.constant.rank"
require "common.constant.dao"
require "common.constant.chat"
require "common.constant.color"
require "common.constant.scene"
require "common.constant.hero"
require "common.constant.attribute"
require "common.constant.audio"
require "common.constant.card"
require "common.constant.player"
require "common.constant.chain"
require "common.constant.language"
require "common.constant.task"
require "common.constant.autoPush"
require "common.constant.union"
require "common.constant.text"
require "common.constant.ref"
require "common.constant.pay"
require "common.constant.activity"

return constant