require "UI.UIManager"
require "UI.UIBase"
require "UI.UIEnum"
require "UI.UIRoot"
require "UI.UIUtil"
require "UI.UIList"
require "UI.UIScrollView"
require "UI.UISpineAni"

require "UI.Login.PnlLogin"
require "UI.Login.PnlLoginView"
require "UI.Login.PnlLink"
require "UI.Login.PnlLinkView"
require "UI.Login.PnlService"
require "UI.Login.PnlServiceView"
require "UI.Register.PnlRegister"
require "UI.Register.PnlRegisterView"
require "UI.ForgetPassword.PnlForgetPassword"
require "UI.ForgetPassword.PnlForgetPasswordView"

require "UI.Common.PnlPromptMsg"
require "UI.Common.PnlPromptMsgView"
require "UI.Common.PnlTip"
require "UI.Common.PnlTipView"
require "UI.Common.PnlTipNode"
require "UI.Common.PnlTipNodeView"

require "UI.Common.PnlStatement"
require "UI.Common.PnlStatementView"
require "UI.Common.CommonBtnsBox"
require "UI.Common.CommonItems"
require "UI.Common.CommonItemItems"
require "UI.Common.CommonUpgradeNewBox"
require "UI.Common.PnlOptions"
require "UI.Common.PnlOptionsView"
require "UI.Common.CommonfilterBox"

require "UI.Main.PnlMain"
require "UI.Main.PnlMainView"
require "UI.Main.PnlPlayerInformation"
require "UI.Main.PnlPlayerInformationView"
require "UI.Main.PnlBuild"
require "UI.Main.PnlBuildView"
require "UI.Main.BuildItem"
require "UI.Main.MuneButton"

require "UI.Loading.PnlLoading"
require "UI.Loading.PnlLoadingView"

require "UI.GM.PnlGMTool"
require "UI.GM.PnlGMToolView"

require "UI.Campaign.PnlCampaign"
require "UI.Campaign.PnlCampaignView"

require "UI.ItemBag.PnlGridItemBag"
require "UI.ItemBag.PnlGridItemBagView"
require "UI.ItemBag.PnlItemBagNew"
require "UI.ItemBag.PnlItemBagNewView"
require "UI.ItemBag.PnlItemResolve"
require "UI.ItemBag.PnlItemResolveView"
require "UI.ItemBag.BagItems"
require "UI.ItemBag.PnlGridNftBag"
require "UI.ItemBag.PnlGridNftBagView"


require "UI.Battle.PnlBattle"
require "UI.Battle.PnlBattleView"
require "UI.Battle.BattleItem"
require "UI.Battle.BattleResultBox"

require "UI.BattleResult.BattleResultStrengthBox"
require "UI.BattleResult.BattleCasualtiesBox"
require "UI.BattleResult.BattleResultRewardBox"

require "UI.Battle.PnlResultView"
require "UI.Battle.PnlResult"

require "UI.Fix.PnlFix"
require "UI.Fix.PnlFixView"
require "UI.Fix.FixItem"

require "UI.HeroHut.PnlHeroHut"
require "UI.HeroHut.PnlHeroHutView"
require "UI.HeroHut.PnlHeroHutItem"

require "UI.WarShip.PnlWarShip"
require "UI.WarShip.PnlWarShipView"

require "UI.Rank.PnlRank"
require "UI.Rank.PnlRankView"
require "UI.Rank.RankItem"

require "UI.Alert.PnlAlert"
require "UI.Alert.PnlAlertView"
require "UI.Alert.PnlAlertNew"
require "UI.Alert.PnlAlertNewView"
require "UI.Alert.PnlAlertRemoveBuilding"
require "UI.Alert.PnlAlertRemoveBuildingView"
require "UI.Alert.PnlAlertResetSkill"
require "UI.Alert.PnlAlertResetSkillView"
require "UI.Alert.PnlAlertShowGift"
require "UI.Alert.PnlAlertShowGiftView"



require "UI.Upgrade.PnlUpgrade"
require "UI.Upgrade.PnlUpgradeView"

require "UI.Soldier.PnlSoldier"
require "UI.Soldier.PnlSoldierView"
require "UI.Soldier.PnlSoldierQuickTrain"
require "UI.Soldier.PnlSoldierQuickTrainView"
require "UI.Soldier.PnlSoldierInstantTrain"
require "UI.Soldier.PnlSoldierInstantTrainView"
require "UI.Soldier.SoldierItems"

require "UI.Institute.PnlInstitute"
require "UI.Institute.PnlInstituteView"
require "UI.Institute.InstituteItem"
require "UI.Institute.PnlForceUpgrade"
require "UI.Institute.PnlForceUpgradeView"
require "UI.Institute.PnlDrawSet"
require "UI.Institute.PnlDrawSetView"
require "UI.Institute.PnlForgeResult"
require "UI.Institute.PnlForgeResultView"

require "UI.Connect.PnlConnect"
require "UI.Connect.PnlConnectView"

require "UI.BuildInfo.PnlBuildInfo"
require "UI.BuildInfo.BuildInfoItem"
require "UI.BuildInfo.PnlBuildInfoView"
require "UI.BuildInfo.PnlPledgeSet"
require "UI.BuildInfo.PnlPledgeSetView"
require "UI.BuildInfo.PnlConstruction"
require "UI.BuildInfo.PnlConstructionView"

require "UI.Setting.PnlSetting"
require "UI.Setting.PnlSettingView"
require "UI.Setting.PnlSettingCdKey"
require "UI.Setting.PnlSettingCdKeyView"
require "UI.Setting.PnlSettingService"
require "UI.Setting.PnlSettingServiceView"
require "UI.Setting.PnlSettingproducer"
require "UI.Setting.PnlSettingproducerView"
require "UI.Setting.PnlSettingWallet"
require "UI.Setting.PnlSettingWalletView"
require "UI.Setting.PnlSettingLanguage"
require "UI.Setting.PnlSettingLanguageView"
require "UI.Setting.SettingItems"
require "UI.Setting.PnlSettingDeleteAccount"
require "UI.Setting.PnlSettingDeleteAccountView"

require "UI.Exchange.PnlQuickExchange"
require "UI.Exchange.PnlQuickExchangeView"

require "UI.Map.PnlMap"
require "UI.Map.PnlMapView"
require "UI.Map.PnlPlanet"
require "UI.Map.PnlPlanetView"
require "UI.Map.MapItems"
require "UI.Map.PnlRename"
require "UI.Map.PnlRenameView"
require "UI.Map.PnlMaterialReward"
require "UI.Map.PnlMaterialRewardView"
require "UI.Map.PnlGvgResult"
require "UI.Map.PnlGvgResultView"
require "UI.Map.PnlSmallMap"
require "UI.Map.PnlSmallMapView"
require "UI.Map.PnlCollections"
require "UI.Map.PnlCollectionsView"
require "UI.Map.PnlMapEntrance"
require "UI.Map.PnlMapEntranceView"

require "UI.BattleReport.BattleReportTopButton"
require "UI.BattleReport.PnlBattleReport"
require "UI.BattleReport.PnlBattleReportView"
require "UI.BattleReport.PnlUnionWarReport"
require "UI.BattleReport.PnlUnionWarReportView"
require "UI.BattleReport.PnlUnionWarReportInfo"
require "UI.BattleReport.PnlUnionWarReportInfoView"
require "UI.BattleReport.PnlWarPlayerInfo"
require "UI.BattleReport.PnlWarPlayerInfoView"

require "UI.MyPlanet.PnlMyPlanet"
require "UI.MyPlanet.PnlMyPlanetView"

require "UI.Routes.PnlRoutes"
require "UI.Routes.PnlRoutesView"

require "UI.Board.PnlBoard"
require "UI.Board.PnlBoardView"
require "UI.Board.BoardItems"

require "UI.Chat.PnlChat"
require "UI.Chat.PnlChatView"
require "UI.Chat.ChatItem"

require "UI.PlayerDetailed.PnlPlayerDetailed"
require "UI.PlayerDetailed.PnlPlayerDetailedView"
require "UI.PlayerDetailed.PlayerDetailedSelectHeadBox"
require "UI.PlayerDetailed.PnlChangeName"
require "UI.PlayerDetailed.PnlChangeNameView"

require "UI.Collect.PnlCollect"
require "UI.Collect.PnlCollectView"

require "UI.Guide.PnlGuide"
require "UI.Guide.PnlGuideView"

require "UI.ItemInfo.PnlItemInfo"
require "UI.ItemInfo.PnlItemInfoView"
require "UI.ItemInfo.PnlItemInfoSmall"
require "UI.ItemInfo.PnlItemInfoSmallView"

require "UI.Mail.PnlMail"
require "UI.Mail.PnlMailView"
require "UI.Mail.PnlAcquisition"
require "UI.Mail.PnlAcquisitionView"
require "UI.Mail.BoxMail"

require "UI.Card.PnlCard"
require "UI.Card.PnlCardView"
require "UI.Card.CardItems"
require "UI.Card.CardGroupEditBox"
require "UI.Card.DrawCardBox"
require "UI.Card.PnlBattleDrawCard"
require "UI.Card.PnlBattleDrawCardView"
require "UI.Card.PnlDrawCardResult"
require "UI.Card.PnlDrawCardResultView"
require "UI.Card.PnlCardDesc"
require "UI.Card.PnlCardDescView"

require "UI.SelectRace.PnlSelectRace"
require "UI.SelectRace.PnlSelectRaceView"
require "UI.SelectRace.SelectRaceItems"

require "UI.Pvp.PnlPvp"
require "UI.Pvp.PnlPvpView"
require "UI.Pvp.PvpItems"
require "UI.Pvp.PnlPvpRank"
require "UI.Pvp.PnlPvpRankView"
require "UI.Pvp.PnlPvpRewardRule"
require "UI.Pvp.PnlPvpRewardRuleView"
require "UI.Pvp.PnlPvpFetch"
require "UI.Pvp.PnlPvpFetchView"
require "UI.Pvp.PnlPvpHistory"
require "UI.Pvp.PnlPvpHistoryView"

require "UI.Pve.PnlPveNew"
require "UI.Pve.PnlPveNewView"
require "UI.Pve.PnlPveDailyReward"
require "UI.Pve.PnlPveDailyRewardView"
require "UI.Pve.PveItems"

require "UI.PveResult.PnlPveResultLose"
require "UI.PveResult.PnlPveResultLoseView"
require "UI.PveResult.PnlPveResultWin"
require "UI.PveResult.PnlPveResultWinView"
require "UI.PveResult.PveResultStarBox"

require "UI.BuyCount.PnlBuyCount"
require "UI.BuyCount.PnlBuyCountView"

require "UI.LeagueRank.PnlLeagueRank"
require "UI.LeagueRank.PnlLeagueRankView"
require "UI.LeagueRank.PnlLeagueRankCoreReward"
require "UI.LeagueRank.PnlLeagueRankCoreRewardView"
require "UI.LeagueRank.PnlLeagueRankReward"
require "UI.LeagueRank.PnlLeagueRankRewardView"

require "UI.Union.PnlUnion"
require "UI.Union.PnlUnionView"
require "UI.Union.PnlUnionNft"
require "UI.Union.PnlUnionNftView"


require "UI.Task.PnlTask"
require "UI.Task.PnlTaskView"
require "UI.Task.TaskItems"
require "UI.Task.PnlTaskReward"
require "UI.Task.PnlTaskRewardView"
require "UI.Task.PnlTaskRewardDesc"
require "UI.Task.PnlTaskRewardDescView"

require "UI.UnionArmy.PnlUnionArmy"
require "UI.UnionArmy.PnlUnionArmyView"
require "UI.UnionArmy.PnlUnionArmyEdit"
require "UI.UnionArmy.PnlUnionArmyEditView"
require "UI.UnionArmy.UnionArmyItems"
require "UI.UnionArmy.UnionArmyEditItems"

require "UI.Edit.PnlEdit"
require "UI.Edit.PnlEditView"
require "UI.Edit.EditItem"

require "UI.EditBattle.PnlEditBattle"
require "UI.EditBattle.PnlEditBattleView"
require "UI.EditBattle.EditBattleItems"

require "UI.NFTTower.PnlNFTTower"
require "UI.NFTTower.PnlNFTTowerView"

require "UI.Rule.PnlRule"
require "UI.Rule.PnlRuleView"

require "UI.Draft.PnlDraft"
require "UI.Draft.PnlDraftView"

require "UI.StarMapPlot.PnlStarMapPlot"
require "UI.StarMapPlot.PnlStarMapPlotView"

require "UI.Headquarters.PnlHeadquarters"
require "UI.Headquarters.PnlHeadquartersView"
require "UI.Headquarters.PnlHeadquartersSkillUpgrade"
require "UI.Headquarters.PnlHeadquartersSkillUpgradeView"
require "UI.Headquarters.PnlChooseSkill"
require "UI.Headquarters.PnlChooseSkillView"
require "UI.Headquarters.PnlRecycleCenter"
require "UI.Headquarters.PnlRecycleCenterView"


require "UI.StarMapItemBag.PnlStarMapItemBag"
require "UI.StarMapItemBag.PnlStarMapItemBagView"

require "UI.PersonalArmy.PnlPersonalArmy"
require "UI.PersonalArmy.PnlPersonalArmyView"
require "UI.PersonalArmy.PersonalArmyItems"
require "UI.DrawCard.PnlDrawCard"
require "UI.DrawCard.PnlDrawCardView"
require "UI.DrawCard.DrawCardResultBox"

require "UI.DrawCard.PnlCardpoolMessage"
require "UI.DrawCard.PnlCardpoolMessageView"

require "UI.Mint.PnlMint"
require "UI.Mint.PnlMintView"
require "UI.Mint.MintItems"
require "UI.Mint.PnlMintNFTList"
require "UI.Mint.PnlMintNFTListView"
require "UI.Mint.PnlMintInfo"
require "UI.Mint.PnlMintInfoView"
require "UI.Mint.PnlMint"
require "UI.Mint.PnlMintView"
require "UI.Mint.MintItems"
require "UI.Mint.PnlMintNFTList"
require "UI.Mint.PnlMintNFTListView"
require "UI.Mint.PnlMintInfo"
require "UI.Mint.PnlMintInfoView"

require "UI.DrawCard.PnlDrawCard"
require "UI.DrawCard.PnlDrawCardView"
require "UI.DrawCard.PnlDrawCardInfo"
require "UI.DrawCard.PnlDrawCardInfoView"

require "UI.Pledge.PnlPledge"
require "UI.Pledge.PnlPledgeView"
require "UI.Pledge.PledgeBox"

require "UI.Shop.PnlShop"
require "UI.Shop.PnlShopView"
require "UI.Shop.ShopItems"
require "UI.Shop.PnlExchangeAlert"
require "UI.Shop.PnlExchangeAlertView"
require "UI.Shop.MoonCardBox"
require "UI.Shop.BuildQueueBox"
require "UI.Shop.AuditMoonCardBox"


require "UI.Shop.PnlPay"
require "UI.Shop.PnlPayView"


require "UI.PersonalQuickSelectArmy.PnlPersonalQuickSelectArmy"
require "UI.PersonalQuickSelectArmy.PnlPersonalQuickSelectArmyView"
require "UI.Reward.PnlReward"
require "UI.Reward.PnlRewardView"
require "UI.Reward.PnlRewardSmall"
require "UI.Reward.PnlRewardSmallView"

require "UI.HyList.PnlHyList"
require "UI.HyList.PnlHyListView"
require "UI.HyList.HyListFirstPlotBox"
require "UI.HyList.HyListItems"
require "UI.HyList.OpenServerUnionRankBox"
require "UI.HyList.OpenServerPVPRankBox"


require "UI.Desc.PnlDesc"
require "UI.Desc.PnlDescView"

require "UI.Shrine.PnlShrine"
require "UI.Shrine.PnlShrineView"
require "UI.Shrine.ShrineItems"

require "UI.Activity.PnlActivity"
require "UI.Activity.PnlActivityView"
require "UI.Activity.ActivityDailyCheckInBox"
require "UI.Activity.AccruingTesBox"
require "UI.Activity.ActivityGiftBox"
require "UI.Activity.ActivityItems"
require "UI.Activity.FirstChargeBox"
require "UI.Activity.OpenAccruingChargeBox"
require "UI.Activity.LimitTimeGoodsBox"
require "UI.Activity.PnlDailyCheck"
require "UI.Activity.PnlDailyCheckView"

require "UI.UnionArmyNew.PnlUnionArmyNew"
require "UI.UnionArmyNew.PnlUnionArmyNewView"
require "UI.UnionArmyNew.UnionArmyNewItems"
require "UI.UnionArmyNew.PnlUnionArmySelect"
require "UI.UnionArmyNew.PnlUnionArmySelectView"
require "UI.UnionArmyNew.PnlAutoSelectArmy"
require "UI.UnionArmyNew.PnlAutoSelectArmyView"


require "UI.NewPlayerLoginAct.PnlNewPlayerLoginAct"
require "UI.NewPlayerLoginAct.PnlNewPlayerLoginActView"
require "UI.NewPlayerLoginAct.NewPlayerLoginActItems"

require "UI.Service.PnlServiceSmall"
require "UI.Service.PnlServiceSmallView"
