cmap = require "map.core"
require "cfg"
require "gg"
require "gg.init"
require "client.init"
require "common.init"
require "scene.init"
require "player.init"
require "gm.init"
require "UI.init"
require "data.init"